#!/usr/bin/env bash

# Singularity containerised baton wrapper script
# Christopher Harrison <ch12@sanger.ac.uk>

set -euo pipefail

stderr() {
  local message="$*"

  [[ -t 2 ]] && message="$(tput setaf 1)${message}$(tput sgr0)"
  >&2 echo "${message}"
}

## Bootstrap

declare BINARY="$(basename "$0")"
declare BIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [[ "${BINARY}" =~ ^baton- ]]; then
  declare SUBCOMMAND="${BINARY#*-}"
  exec "${BIN_DIR}/baton" "${SUBCOMMAND}" "$@"
fi

declare SINGULARITY
if ! SINGULARITY="$(command -v singularity)"; then
  stderr "Singularity not found!"
  exit 1
fi

declare JQ
if ! JQ="$(command -v jq)"; then
  stderr "jq not found!"
  exit 1
fi

declare IMAGE_EXT="simg"
[[ "$("${SINGULARITY}" --version)" =~ ^3\. ]] && IMAGE_EXT="sif"

declare IMAGE
if ! IMAGE="$(command -v "baton.${IMAGE_EXT}")"; then
  stderr "baton image not found in PATH; checking for local copy..."

  IMAGE="${BIN_DIR}/baton.${IMAGE_EXT}"
  if ! [[ -e "${IMAGE}" ]]; then
    stderr "Local baton image not found; building..."
    "${SINGULARITY}" build "${IMAGE}" "${BIN_DIR}/baton.def"
  fi
fi

declare IRODS_ENVIRONMENT_FILE="${IRODS_ENVIRONMENT_FILE-${HOME}/.irods/irods_environment.json}"
if ! [[ -e "${IRODS_ENVIRONMENT_FILE}" ]]; then
  stderr "iRODS environment configuration not found!"
  exit 1
fi

to_mount() {
  exists() {
    local path

    while read -r path; do
      [[ -e "${path}" ]] && echo "${path}"
    done
  }

  (
    # iRODS environment configuration
    echo "${IRODS_ENVIRONMENT_FILE}"

    # iRODS configuration dependencies
    "${JQ}" -r --argjson keys '[
      "irods_authentication_file",
      "irods_ssl_ca_certificate_file",
      "irods_plugin_home"
    ]' 'to_entries | map(select(.key == $keys[])) | .[].value' "${IRODS_ENVIRONMENT_FILE}"

    # Kerberos configuration, if required
    # TODO Untested
    if [[ "$("${JQ}" -r '.irods_authentication_scheme == "KRB"' "${IRODS_ENVIRONMENT_FILE}")" == "true" ]]; then
      echo "/etc/krb5.conf"
    fi
  ) \
  | sort \
  | uniq \
  | exists \
  | paste -sd,
}

## Entrypoint

main() {
  local app="${1-}"
  local mounts="$(to_mount)"

  local -a run_args=("--containall")
  local -a img_args

  if grep -qx -- "${app}" <("${SINGULARITY}" apps "${IMAGE}"); then
      # The first argument corresponds to an app within the image
      run_args+=("--app" "${app}")
      shift
  fi

  # Transpose baton arguments
  local this
  local last="foo"
  while (( $# )); do
    this="$1"

    # Look for --file arguments to add to the list of mounts
    # FIXME What happens if file is "-" (i.e., stdin) or a FIFO, etc.?
    if [[ "${last}" == "--file" ]]; then
      this="$(readlink -f "${this}")"
      mounts="${mounts},${this}"
    fi

    img_args+=("${this}")
    last="${this}"
    shift
  done

  # Add bind mounts into runtime arguments and launch
  run_args+=("--bind" "${mounts}")
  "${SINGULARITY}" run "${run_args[@]}" "${IMAGE}" "${img_args[@]+"${img_args[@]}"}"
}

main "$@"
